#ifndef COMMANDER_GBC_CONSTANTS_H
#define COMMANDER_GBC_CONSTANTS_H

#define MAX_PLAYERS 8u
#define MAX_COMMANDERS_PER_PLAYER 2u
#define MAX_CUSTOM_COUNTERS 4u
#define MAX_NAME_LENGTH 8u

#define DEFAULT_STARTING_LIFE 40
#define LIFE_WARNING_THRESHOLD 5
#define DEFAULT_POISON_THRESHOLD 10u
#define DEFAULT_COMMANDER_DAMAGE_THRESHOLD 21u

#define MIN_LIFE_TOTAL (-32767 - 1)
#define MAX_LIFE_TOTAL 32767

#define NO_PLAYER (-1)

#endif
