#ifndef COMMANDER_GBC_SPLASH_ASSETS_H
#define COMMANDER_GBC_SPLASH_ASSETS_H

#include <stdint.h>

#define SPLASH_TILE_WHITE_MANA 128u
#define SPLASH_TILE_BLUE_MANA 129u
#define SPLASH_TILE_BLACK_MANA 130u
#define SPLASH_TILE_RED_MANA 131u
#define SPLASH_TILE_GREEN_MANA 132u
#define SPLASH_TILE_ACCENT 133u
#define SPLASH_TILE_FIRST SPLASH_TILE_WHITE_MANA
#define SPLASH_TILE_COUNT 6u

extern const uint8_t splash_tiles[SPLASH_TILE_COUNT * 16u];

#endif
