"""Shared limits and default values for the Python rules engine."""

MIN_PLAYERS = 2
DEFAULT_PLAYERS = 4
MAX_PLAYERS = 8

DEFAULT_STARTING_LIFE = 40
LIFE_WARNING_THRESHOLD = 5

DEFAULT_POISON_THRESHOLD = 10
POISON_WARNING_THRESHOLD = 8

DEFAULT_COMMANDER_DAMAGE_THRESHOLD = 21
COMMANDER_DAMAGE_WARNING_THRESHOLD = 18
MAX_COMMANDERS_PER_PLAYER = 2

MAX_CUSTOM_COUNTERS = 4
MAX_NAME_LENGTH = 8

DAY_NIGHT_NONE = 0
DAY = 1
NIGHT = 2
